openapi: 3.1.1

info:
  title: BaroLab API
  version: 0.0.1

servers:
  - url: http://localhost:8080

security:
  - bearerAuth: []


tags:
  - name: Users
  - name: Admins
  - name: Posts
  - name: Comments

paths:
  /login:
    post:
      security: []
      tags:
        - Users
      requestBody:
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /sign-up:
    post:
      security: []
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users:
    get:
      summary: Get all Users
      tags:
        - Users
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/{userId}:
    get:
      parameters:
        - $ref: '#/components/parameters/userId'
      summary: Get User by ID
      tags:
        - Users
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User' 
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404: 
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/{userId}/activate:
    put:
      parameters:
        - $ref: '#/components/parameters/userId'
      tags:
        - Users
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/{userId}/block:
    put:
      parameters:
        - $ref: '#/components/parameters/userId'
      tags:
        - Users
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/{userId}/role:
    put:
      parameters:
        - $ref: '#/components/parameters/userId'
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              type: string
              enum: [ USER, SUPERUSER, ADMIN, SUPER_ADMIN ]
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /post:
    post:
      tags:
        - Posts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        200:
          description: OK
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Get all Posts
      tags:
        - Posts
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /post/{postId}:
    get:
      parameters:
        - $ref: '#/components/parameters/postId'
      summary: Get Post by ID
      tags:
        - Posts
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post' 
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /post/{postId}/activate:
    put:
      parameters:
        - $ref: '#/components/parameters/postId'
      tags:
        - Posts
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /post/{postId}/block:
    put:
      parameters:
        - $ref: '#/components/parameters/postId'
      tags:
        - Posts
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /post/{postId}/comment:
    post:
      parameters:
        - $ref: '#/components/parameters/postId'
      tags:
        - Comments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        200:
          description: OK
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Get all Comments
      tags:
        - Comments
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /post/{postId}/comment/{commentId}:
    get:
      parameters:
        - $ref: '#/components/parameters/postId'
        - $ref: '#/components/parameters/commentId'
      summary: Get Comment by ID
      tags:
        - Comments
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /post/{postId}/comment/{commentId}/activate:
    put:
      parameters:
        - $ref: '#/components/parameters/postId'
        - $ref: '#/components/parameters/commentId'
      tags:
        - Comments
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /post/{postId}/comment/{commentId}/block:
    put:
      parameters:
        - $ref: '#/components/parameters/postId'
        - $ref: '#/components/parameters/commentId'
      tags:
        - Comments
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    commentId:
      name: commentId
      in: path
      required: true
      schema:
        type: string 
        format: uuid
      description: Id of Comment

    postId:
      name: postId
      in: path
      required: true
      schema:
        type: string 
        format: uuid
      description: Id of Post

    userId:
      name: userId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: ID of the User

  schemas:
    Comment:
      type: object
      required:
        - id
        - post_id
        - user_id
        - text
        - status
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          example: 38ca31a9-a336-4087-ac97-d1ed40a2778e
        post_id:
          type: string
          format: uuid
          example: 38ca31a9-a336-4087-ac97-d1ed40a2778e
        user_id:
          type: string
          format: uuid
          example: 38ca31a9-a336-4087-ac97-d1ed40a2778e
        text:
          type: string
          example: Something cool maybe
        status:
          type: string 
          enum: [ ACTIVE, BLOCKED ]
          example: ACTIVE
          readOnly: true
        created_at:
          type: string
          format: date-time
          example: 2021-09-20T12:00:00Z
        updated_at:
          type: string
          format: date-time
          example: 2021-09-20T13:41:22Z


    Post:
      type: object
      required:
        - id
        - user_id
        - rating
        - status
        - title
        - content
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          example: 38ca31a9-a336-4087-ac97-d1ed40a2778e
          readOnly: true
        user_id:
          type: string
          format: uuid
          example: 38ca31a9-a336-4087-ac97-d1ed40a2778e
          readOnly: true
        rating:
          type: integer
          example: 0
          readOnly: true
        status:
          type: string 
          enum: [ ACTIVE, BLOCKED ]
          example: ACTIVE
          readOnly: true
        title:
          type: string
          example: Post name
        content:
          type: string 
          example: content
        created_at:
          type: string
          format: date-time
          example: 2021-09-20T12:00:00Z
          readOnly: true
        updated_at:
          type: string
          format: date-time
          example: 2021-09-20T13:41:22Z
          readOnly: true

    User:
      type: object
      required:
        - id
        - login
        - email
        - status
        - role
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          example: 38ca31a9-a336-4087-ac97-d1ed40a2778e
          readOnly: true
        login:
          type: string
          example: login
        email:
          type: string
          format: email
          example: test@gmail.com
        status:
          type: string
          enum: [ ACTIVE, BLOCKED ]
          example: ACTIVE
          readOnly: true
        role:
          type: string
          enum: [ USER, VIP ]
          example: USER
        created_at:
          type: string
          format: date-time
          example: 2021-09-20T12:00:00Z
          readOnly: true
        updated_at:
          type: string
          format: date-time
          example: 2021-09-20T13:41:22Z
          readOnly: true

    TokenResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: JWT token.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ik

    LoginRequest:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
          example: login
        password:
          type: string
          format: password
          example: qwerty123456

    SignUpRequest:
      type: object
      required:
        - login
        - email
        - password
      properties:
        login:
          type: string
          example: login
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          example: qwerty123456
          writeOnly: true

    Error:
      type: object
      properties:
        message:
          type: string
          example: Error message.